### ISSUE TITLE
Refactor index.js:Home

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#1]
I've selected [**index.js:Home**](https://github.com/lelouchB/final-space-api/blob/02721df95fde8efea551d5d46891b324201e20f1/frontend/src/pages/index.js#L9-L156) for refactoring, which is a unit of **146** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by cjdeleon62** [comment]
Hi! Can I take this issue?

**Comment by lelouchB** [comment]
Ofcourse @cjdeleon62 
Let me assign this to you.

Thanks 😊

**Comment by lelouchB** [comment]
@cjdeleon62 
It doesn't exactly have to be 15 lines.

Just a little small or separate components are fine tooo.

Thanks
