### ISSUE TITLE
Complete Greetings workflow

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#107]
I started on creating Gretting's workflow but didn't complete it.

It can be found here
https://github.com/lelouchB/final-space-api/blob/main/.github/workflows/greetings.yml

Complete this with some fun and comic quotes or references to the show, it all about your creativity.
Chookity! Chookity!

P.S. Encourage people to start this repo.  :)

**Comment by lelouchB** [comment]
@MrDoomy 
Are you interested in this?

**Comment by MrDoomy** [comment]
Hi @lelouchB 👋
For sure, I can push you something tonight 😎

**Comment by lelouchB** [comment]
hey @MrDoomy 
Any word on this?

**Comment by MrDoomy** [comment]
Oh sorry! 🙏
I pushed something here: https://github.com/lelouchB/final-space-api/pull/116
What do you think about this? 🤔
