### ISSUE TITLE
Add status icon to Character endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#115]
If we can send a `character` status icon, for example a **green**  filled circle for a character that is alive.

It will save a lot of time for devs who are trying to show status using colored icons.

For example
![image](https://user-images.githubusercontent.com/45850882/95587187-5b029980-0a5f-11eb-882f-4369f18c8232.png)

For this we will have to create an icons (preferrably 50x50) jpeg. We only need three icons

-  Alive - Green Filled Circle
-  Dead/  Deceased  - Red Filled Circle
-  Operational - Yellow Filled Circle 

You can use any icon from web (free icon), or create one in paint.
Just head over to paint and resize the area to 50x50px and create a circle, then fill it with proper color. Should be done in a few times..

Let me know if you have any question

**Comment by ErickLemos** [comment]
i can keep it

**Comment by lelouchB** [comment]
Hey @ErickLemos 
Can you also update the docs with issue.

Like the schema and example requests, etc. in `characteer.md`

**Comment by ErickLemos** [comment]
yes i can, i will do it! 
Something more?

**Comment by lelouchB** [comment]
> 
> 
> yes i can, i will do it!
> Something more?

Not right now but if I think of something, will let you know.

Thanks

**Comment by harsh599** [comment]
Hello @lelouchB  I have been so near about achieving the results just need your help as my images are breaking dont know why I have kept my icons in img folder and accessing them as 'img/filename.jpg' but dont get the point as why images are breaking

It would be great if you can help!!
![image](https://user-images.githubusercontent.com/31313683/95624687-e5b1bb80-0a94-11eb-840c-34abd99b22d0.png)

**Comment by lelouchB** [comment]
> Hello @lelouchB I have been so near about achieving the results just need your help as my images are breaking dont know why I have kept my icons in img folder and accessing them as 'img/filename.jpg' but dont get the point as why images are breaking
> 
> It would be great if you can help!!
> ![image](https://user-images.githubusercontent.com/31313683/95624687-e5b1bb80-0a94-11eb-840c-34abd99b22d0.png)

Hey @harsh599 
No problem, I think know the problem but just to be sure can you send a PR with your code.

Thanks

**Comment by harsh599** [comment]
> > Hello @lelouchB I have been so near about achieving the results just need your help as my images are breaking dont know why I have kept my icons in img folder and accessing them as 'img/filename.jpg' but dont get the point as why images are breaking
> > It would be great if you can help!!
> > ![image](https://user-images.githubusercontent.com/31313683/95624687-e5b1bb80-0a94-11eb-840c-34abd99b22d0.png)
> 
> Hey @harsh599
> No problem, I think know the problem but just to be sure can you send a PR with your code.
> 
> Thanks

Yes Sure Thankyou @lelouchB

**Comment by harsh599** [comment]
Hey I am facing issue file comitting my changes I am stuck at point to push my content to repo its showing access denied issue
![image](https://user-images.githubusercontent.com/31313683/95645971-7ca46500-0ae1-11eb-8898-b3ede9391644.png)

**Comment by lelouchB** [comment]
Hey @harsh599 
I guess your repo is not updated with the latest commits, might wanna do that before pushing changes?

**Comment by harsh599** [comment]
> Hey @harsh599
> I guess your repo is not updated with the latest commits, might wanna do that before pushing changes?

Hello @lelouchB  I have made a PR request successfully kindly check it out.

**Comment by lelouchB** [comment]
@ErickLemos 
Any word on this?

**Comment by ErickLemos** [comment]
> @ErickLemos 
> Any word on this?

hello, sorry for the delay, I had some personal problems, I will return to the project tomorrow!

**Comment by lelouchB** [comment]
> > @ErickLemos 
> > Any word on this?
> 
> hello, sorry for the delay, I had some personal problems, I will return to the project tomorrow!

Yeah yeah 
No rush 
Take your time 👍

**Comment by ErickLemos** [comment]
I went back to the project, spent a few days out, sorry.

**Comment by lelouchB** [comment]
@harsh599 
You up for this?

**Comment by guzbarraf** [comment]
Hi @lelouchB is this issue still available?

**Comment by lelouchB** [comment]
@guzbarraf 
Yes
I will assign it you

**Comment by guzbarraf** [comment]
thanks @lelouchB, tomorrow I'll upload the PR
