### ISSUE TITLE
Add Prettier and Husky to frontend 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#120]
@JuanVqz  Did a great job adding husky and prettier to `backend` to format code when commiting.
See #112 

```
   "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "*.js": "eslint --cache --fix",
        "*.{js,css,md}": "prettier --write"
    }
```

Add same thing to `frontend` folder.

**Comment by binkpitch** [comment]
Can i take this issue?

**Comment by lelouchB** [comment]
@binkpitch 
Sure
I have assigned this to you.
Let me know if you have any questions.

**Comment by binkpitch** [comment]
@lelouchB Any specific linting settings (for `.eslintrc` and `.prettierc`) that I should be aware of?

**Comment by lelouchB** [comment]
@binkpitch 
Nothing special, I am fine with standard stuff for these.
Here is code for backend
https://github.com/lelouchB/final-space-api/blob/main/backend/.eslintrc.js
https://github.com/lelouchB/final-space-api/blob/main/backend/.prettierrc.json
