### ISSUE TITLE
Add `serve-favicon` to backend

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#129]
Add `serve-favicon` to `backend/server.js`

Reources: https://www.npmjs.com/package/serve-favicon

**Comment by ayush015** [comment]
Can I try this ?

**Comment by lelouchB** [comment]
@ayush015 
Sure 👍

**Comment by lelouchB** [comment]
Assigned it you.

Let me know if you have any questions.

**Comment by lelouchB** [comment]
Hey @ayush015 
Any word on this ?

**Comment by ayush015** [comment]
working on it . Will try to finish it by today

**Comment by ayush015** [comment]
@lelouchB Done please review #131
