### ISSUE TITLE
Embed Weibenfalk video on Final Space API  to Examples section 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#135]
Embed Weibenfalk video in Examples section 

https://youtu.be/zmwG5lYQYRo

P.S. make sure to add links to his Twitter, website etc.

**Comment by tiana30** [comment]
hello i want to take this issue

**Comment by lelouchB** [comment]
Awesome 
Assigning to you @tiana30

**Comment by lelouchB** [comment]
Hey @tiana30 
This resource maybe helpful 
https://www.slideas.app/blog/how-to-embed-a-vimeo-or-youtube-video-in-markdown/

**Comment by lelouchB** [comment]
Hey @tiana30 
Any update on this?

**Comment by adityatandon007** [comment]
@lelouchB can I take this if it is not being taken. One more thing does this video needs to be embedded to the https://github.com/lelouchB/final-space-api/blob/main/README.md section or inside the docs in intro.md

**Comment by lelouchB** [comment]
Hey @adityatandon007 
Thanks for your interest, I have pinged @tiana30 
Let's just wait a day for her reply  and there is still no updates, I will assign this issue to you.

The video will in a separate page under `Examples` section in the docs.
Hope that answers your question

**Comment by tiana30** [comment]
hello, i'm sorry to inform you i think there is something wrong with my internet connection i can't clone this project to my computer.
So you can assign anyone who interested.

**Comment by lelouchB** [comment]
@tiana30  No problem 

@adityatandon007  assigned to you 
Let me know if you have any questions

**Comment by adityatandon007** [comment]
@lelouchB please review and merge
