### ISSUE TITLE
Highlight import lines in Example pages

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#136]
Highlight important lines in the code snippets in Examples. 

For example in the `frontend/docs/react.mdx`, you can highlight the `useEffect()` and axios fetching code lines.

Resource
https://v2.docusaurus.io/docs/markdown-features/#line-highlighting

P.S just highlight the few important lines like where data is fetched, used, etc.

**Comment by lelouchB** [comment]
Assigned to @bgildson

**Comment by bgildson** [comment]
Hey @lelouchB, could I take this one?

**Comment by lelouchB** [comment]
Done ✔

**Comment by lelouchB** [comment]
Hey @bgildson 
Any update on this?

**Comment by bgildson** [comment]
I have added highlight to the `frontend/docs/react.mdx` in the main code snippets pieces on #137

**Comment by lelouchB** [comment]
> 
> 
> I have added highlight to the `frontend/docs/react.mdx` in the main code snippets pieces on #137

Yes, I saw that 
Great work 👍 


But as said in my review, the issue is for all the examples and not just one.
So, please update other examples too.


Thanks
