### ISSUE TITLE
Quotes Endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#140]
*What is this `./endpoint` about ?*
Final Space has some great fun quotes by its characters. 
This endpoint will be sending quotes.

Maybe after initial setup add a filter that will send quotes from a specific character.

*What is the schema ?*
```
quote : 'Quote',
by : 'Name of character',
character : 'URL to that character endpoint',
image: 'URL to Character Image'
```

**Comment by Mayank0255** [comment]
@lelouchB could I try this one?

P.S. - I am new to Open Source Contribution, but, I am not new to web development with React, Node.js and MongoDB

**Comment by lelouchB** [comment]
@Mayank0255 
Ofcourse 
This is the endpoint suggestion issue of Quotes endpoint 

Can you comment on #141 so I can assign it to you 

Thanks

**Comment by Mayank0255** [comment]
@lelouchB sure will do that right away and kindly explain it to me a little that you want this endpoint to be built with our imagination right? You have provided us what it should do and a brief about the schema

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB sure will do that right away and kindly explain it to me a little that you want this endpoint to be built with our imagination right? You have provided us what it should do and a brief about the schema

Answered here https://github.com/lelouchB/final-space-api/issues/141#issuecomment-728718700

**Comment by Mayank0255** [comment]
@lelouchB 

After you would have added the quotes data to the database, could you provide me with the `.env` file as or else to test out the endpoints I would have to add some data of my own

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB
> 
> After you would have added the quotes data to the database, could you provide me with the `.env` file as or else to test out the endpoints I would have to add some data of my own

Are you talking about testing quotes endpoint or all endpoints in general ?

**Comment by Mayank0255** [comment]
> Are you talking about testing quotes endpoint or all endpoints in general ?
@lelouchB Ya I'm talking about that only

**Comment by lelouchB** [comment]
For active endpoints you can run `npm run seed`  in the backend directory which will fill your local MongoDB collection with data from API
You can manually add `quotes` to that collection for local development.

Refer here. https://github.com/lelouchB/final-space-api/blob/4a0b007ce782c45db877882aee560240916af7a9/backend/package.json#L13

**Comment by Mayank0255** [comment]
Cool got it

**Comment by lelouchB** [comment]
@Mayank0255 
Quotes endpoint is live.

Thanks to your contribution, I was able to ship it into production.

https://finalspaceapi.com/blog/quote
https://finalspaceapi.com/api/v0/quote

**Comment by Mayank0255** [comment]
@lelouchB 

Thanks a lot Ashutosh and the mention on the blog also means a lot.

**Comment by lelouchB** [comment]
NP
👍 
If you want you can also create an example for this endpoint under the Examples section
https://github.com/lelouchB/final-space-api/issues/32
 
Thanks :)

**Comment by Mayank0255** [comment]
> NP
> 👍
> If you want you can also create an example for this endpoint under the Examples section
> #32
> 
> Thanks :)

Not at the moment but will ping you later on if I get time for it
