### ISSUE TITLE
Contribute data to Quote endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#141]
Contirbute data to  `quote` endpoint. 

Make the PR to `endpoint` branch.

**Comment by Mayank0255** [comment]
@lelouchB I would like to take up this issue and for that I want you to reactify some of my queries as well like what's the process of contributing data to any endpoint as there ain't any CREATE or UPDATE routes, or something else.

**Comment by lelouchB** [comment]
@Mayank0255 
Sure so this issue is specific for the contributing data to the quote endpoint.

For this issue, you will have to send a PR with different quotes in a JSON format to the `endpoint` branch.

You can google Final Space quotes and copy the quotes from there and create one quote with indormation as per the schema.
For example

```
{
quote :"Get Off My Cheeks HUE!",
by:"Gary Goodspeed",
character:"https://finalspaceapi.com/api/v0/character/1",
image:"https://finalspaceapi.com/api/character/avatar/gary_goodspeed.jpg"
}
```

After around 30 - 50 quotes, I will create more issues on this endpoint.

Are you still interested in this issue?


Hope this answers your question. 
Let me know if you have any other question.

**Comment by Mayank0255** [comment]
@lelouchB I think I am interested in it just two things that in the endpoint branch should I pull from `main` too or just work with the existing code in endpoint? Secondly this json I can prepare and where do I have to put it? Should I create a Quotes folder and add the json file over there?

**Comment by lelouchB** [comment]
You can work with the existing code, after the JSON is completed. I will add it to the database so it doesn't matter where you add the JSON in `endpoint` branch.
Sure, create a `quotes` folder, if you want.

**Comment by Mayank0255** [comment]
@lelouchB 

Perfect will begin with the json first then create the endpoint. Right?

**Comment by lelouchB** [comment]
Yeah
So, Should I assign this to you?

**Comment by Mayank0255** [comment]
@lelouchB ya please do that
