### ISSUE TITLE
Create route for Quotes Endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#143]
#140 
To Do
- Create `quote.model.js` under `backend/models`
- Create `quote.api.js` in `backend/controllers` directory
- Add `quotes` to `routes/routes.js`
- Add `quote` to `config/endpoints.js`

**Comment by Mayank0255** [comment]
@lelouchB What's the difference between the two issues?

**Comment by lelouchB** [comment]
> @lelouchB What's the difference between the two issues? 
> 

That is the global issue around this whole endpoint.

This is a specific issue.

After this is done. I will create issues for documentation. 

Can I assign this to you?

**Comment by Mayank0255** [comment]
Sure no issues

**Comment by Mayank0255** [comment]
@lelouchB What routes do you need me to add?

Just `GET all quotes`?

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB What routes do you need me to add?
> 
> Just `GET all quotes`?

Yes for now `GET all quotes` is fine.
I am also thinking of adding a filter of name in this endpoint where users can give a query something like `/api/v0/quote/gary` or ` /api/v0/quote?by=gary_goodspeed`. Just a thought.

But yeah, for now `GET` all is perfect.
Also add the `sort` and `limit` config as added in other endpoints.

**Comment by Mayank0255** [comment]
@lelouchB 

Cool would do all that and ping me after this issue when you think of implementing the filtering thing and other routes

**Comment by lelouchB** [comment]
Of course
Will do so.

**Comment by Mayank0255** [comment]
Where to write the test for the route? And I have to write the docs for quotes as well write?

**Comment by lelouchB** [comment]
There are no tests as of now. It is under development by @JuanVqz 

It's your choice, you can write the docs or just work on the code.
I will either create an issue and assign someone for the documentation or write them myself.

**Comment by Mayank0255** [comment]
Okay then will just create a PR
