### ISSUE TITLE
Examples button on Homepage points to redundant route.

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#157]
![image](https://user-images.githubusercontent.com/45850882/129574646-aecf0d47-8418-4fbb-8017-0ad7fbc1fa84.png)

**Comment by ranjithjupaka** [comment]
i would like to work on this issue

**Comment by lelouchB** [comment]
Hey @ranjithjupaka 
Sure

Its simple enough, the Examples button on homepage should point to https://finalspaceapi.com/docs/examples/react/


It would not even require you to set up the project.

I'll assign this to you.

Let me know if you have any questions.

**Comment by ranjithjupaka** [comment]
Tq sir Sent from Mail for Windows From: ASHUTOSH KUMAR SINGHSent: 16 August 2021 19:51To: lelouchB/final-space-apiCc: Ranjith jupaka; MentionSubject: Re: [lelouchB/final-space-api] Examples button on Homepage points to redundant route. (#157) Hey @ranjithjupakaSureIts simple enough, the Examples button on homepage should point to https://finalspaceapi.com/docs/examples/react/It would not even require you to set up the project.I'll assign this to you.Let me know if you have any questions.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ranjithjupaka** [comment]
ok sir

**Comment by ranjithjupaka** [comment]
hello, sir I am a bit confused regarding the bug actually I was literally breaking my head to understand the bug. finally what I understood was presently the  Examples button on the homepage is  pointing to https://finalspaceapi.com/docs/examples/react/
but it should point to https://finalspaceapi.com/docs/react/ (as seen from the above image)

**Comment by ranjithjupaka** [comment]
hello, sir I understood what is the bug is! I will soon  fix it  thank you, but I did not understand what do you mean by **you would not even require you to set up the project**

**Comment by lelouchB** [comment]
Its pointing to https://finalspaceapi.com/docs/react/ but it should point
to https://finalspaceapi.com/docs/examples/react/

The above image is the error.

**Comment by ranjithjupaka** [comment]
ha understood sir thank you how can i fix that without set up??

**Comment by lelouchB** [comment]
> hello, sir I understood what is the bug is! I will soon fix it thank you, but I did not understand what do you mean by **you would not even require you to set up the project**

I meant that since the change is only a couple of lines, it's not specifically needed to install the project on your local machine. 

This file needs to be edited https://github.com/lelouchB/final-space-api/blob/main/frontend/src/pages/Components/Body/_InfoCointainer.js

You can just edit it in the GitHub itself

**Comment by ranjithjupaka** [comment]
ok sir I will do it now

**Comment by lelouchB** [comment]
Also, no need for Sir

Even when contributing to large codebases of Mozilla, MediaWiki, etc,  
Project maintainers amd other contributors prefer if you call them with their names.  


So, just Ashutosh is fine :)
