### ISSUE TITLE
Contribute data to Location Endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#16]
# Reopened to include Season 3 locations

The `/location` endpoint is currently in progress.

You can contribute data for locations in Final Space in the given schema.

Resource: https://final-space.fandom.com/wiki/Category:Location

P.S. You can leave the field for img_url.

You can send a PR with the data in  JSON format to the `endpoint` branch under `location` folder.

Here is the schema for `/location` endpoint:

|Key|Type|Description|
|---|---|---|
|id|int|The id of the location.(Starts with 1)
|name|string|The name of the location.
|type|array|Type of location.
|inhabitants|string|Inhabitants of the location.
|notable_residents|array|Notable residents(if any).
|img_url|string (url)|Image of the location.

(leave fields with no information as `Unknown` or just empty.)

P.S.: The information about locations is less, so 5-10 main locations data is enough.

This may include but not limited to the following location.

- [x]   **Indicates that the data exists for that episode.**

- [x] Earth
- [x] Final Space
- [x] Tera Con Prime
- [x] Inner Space
- [x] Yarno
- [x] Dark Zone
- [x] Deathcropolis
- [x]  Lazarus Trap
- [x] The Order of the Twelve

**Comment by GerryLarios** [comment]
Hello, Can I help with this issue as well?

**Comment by lelouchB** [comment]
Ofcourse, @GerryLarios  

This should be pretty simple as there is not much location information available on the fandom.

I would request you to give every location a read on fandom, they are not that big and will with generating data.

If you have any question or idea about the schema, do let me know.

Thanks, assigning this to you. 👍

**Comment by lelouchB** [comment]
@GerryLarios 
Any update on this?

Thanks

**Comment by GerryLarios** [comment]
@lelouchB working on in, I'll get it done in a few hours.

**Comment by lelouchB** [comment]
@GerryLarios 
Awesome
Looking forward to it.

Have you checked out this 
https://finalspaceapi.com/blog/episode

**Comment by GerryLarios** [comment]
@lelouchB thanks for the mention! <3

**Comment by lelouchB** [comment]
Hey @GerryLarios 
https://finalspaceapi.com/blog/location
Its live

**Comment by GerryLarios** [comment]
> Hey @GerryLarios
> https://finalspaceapi.com/blog/location
> Its live

Thanks for the mention, looks nice 👍

**Comment by lelouchB** [comment]
Hey @GerryLarios 
If interested, please let me know. Else I will re assign this issue to someone else.

Thanks
