### ISSUE TITLE
Server 500 on https://finalspaceapi.com/api

### ISSUE THREAD

**Issue by HSTsou** [lelouchB/final-space-api#163]
**Describe the bug**

Does seems to the following server is shutdown?
https://finalspaceapi.com/docs/endpoints/character#get-all-characters

**To Reproduce**
1. go to https://finalspaceapi.com/docs/endpoints/character#get-all-characters
2. click https://finalspaceapi.com/api/v0/character/

**Expected behavior**
get the right response

<img width="518" alt="image" src="https://github.com/lelouchB/final-space-api/assets/6565838/b7260e21-ea73-4ec2-8958-63c13b854134">

**Comment by lelouchB** [comment]
@HSTsou 
Thanks for bringing this to my notice, I am checking why this is happening

**Comment by lelouchB** [comment]
Hey @HSTsou 
I am still trying to resolve this, somehow I lost access to cloud server login where the API is deployed so its getting trickier to debug

**Comment by johdasgran** [comment]
It's already working for me
https://johdasgran.github.io/game/
![image](https://github.com/lelouchB/final-space-api/assets/69698539/abf66adc-b8e7-4b4b-a114-b09e3c55302c)

**Comment by lelouchB** [comment]
It started working on its own :) 
Please share your project once its done
