### ISSUE TITLE
Serve images in next-gen formats - (WebP)

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#17]
Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption.

Change the format of the following images to **WebP**.
(Note: this is only for the [images](https://github.com/lelouchB/final-space-api/tree/main/frontend/static/img) under `frontend/static/img` which are displayed on the landing page.)

- [x]   **Indicates that WebP  format exists for that image.**

- [x] gary_goodspeed.jpg
- [x] avocato.jpg
- [x] kvn.jpg
- [x] mooncake.jpg
- [x] little_cato.jpg
- [x] quinn_ergon.jpg
- [x] ash_graven.jpg

**Comment by AldoTu** [comment]
Hi @lelouchB, I can help you with this.

**Comment by lelouchB** [comment]
Hey @AldoTu 
I will assign this issue to you.
Thanks

**Comment by AldoTu** [comment]
Done @lelouchB :)

**Comment by lelouchB** [comment]
@AldoTu 
Thanks for your contribution 👍 
Feel free to work on other issues or create your own.

I am sure there are lot o things that you can help with like documentation, README updates, etc.

Looking forward to your future contributions. 💯
