### ISSUE TITLE
 Contribute data to Character endpoint (40 characters exists)

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#18]
The `/character` endpoint currently has **~25~**  **~40~** characters.  (Update #25 )

There are still few characters that we can add to this endpoint.

Contribute data for individual characters of Final Space in the given schema. 

Resource: https://final-space.fandom.com/wiki/Category:Characters

P.S. You can leave the field for `img_url`. 

You can send a PR with the data in JSON format to the `endpoint` branch under `character` folder.

*Please check if the data for that character exists.*

Here is the schema for `/character` endpoint:

|Key|Type|Description|
|---|---|---|
|id|int|The id of the character (starting from 1).
|name|string|The name of the character.
|status|string|The status of the character.
|species|string|The species of the character.
|gender|string|The gender of the character.
|hair|string|The hair color of the character.
|origin|object|Name of the character's origin location.
|abilities|array|Different abilities of character.
|alias|array|Different names of character.
|img_url|string (url)|Link to the character's image.

**Comment by stevenjburrows** [comment]
I will add some more to this for you.

**Comment by lelouchB** [comment]
Thanks @stevenjburrows 
I will assign this issue to you then.

**Comment by stevenjburrows** [comment]
I will add some more to this for you what do you want for origin as the wiki doesn't mention it for the three I have looked at

**Comment by lelouchB** [comment]
Hey, 
You can add `Unknown` in such cases,

There are many characters with less information,

You can refer here for more such queries,

https://finalspaceapi.com/api/v0/character

Thanks

**Comment by lelouchB** [comment]
Update : After #25 there are 40 characters in the database now, I am keeping this issue open,  just in case someone come across a character that isn't present in the database and want to work on it.
