### ISSUE TITLE
Create a logo for this API

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#20]
Currently, this image is used as logo and favicon.

![](https://finalspaceapi.com/img/logo.png)

# Create a new logo for this API

I would suggest becoming familiar with Final Space will be beneficial.
Even Mooncake can be used as a logo.

It's upto your imagination.

**Comment by chandresh1339** [comment]
Do you want a NEW LOGO created for Final Space? . If yes, please I can work on this request.

**Comment by lelouchB** [comment]
@chandresh1339  
Hey Hey
Yes, I want a logo designed specific for this project.

I will assign this issue to you.
Are you familiar with Final Space?

I would love if you can add few characters maybe [Mooncake](https://final-space.fandom.com/wiki/Mooncake) in the logo, and if you are designing something text based. Make sure it reads **Final Space API**.


Let me know if you have any questions.
Looking forward to your contribution.

**Comment by kavita121** [comment]
Hey can I still work on this?

**Comment by lelouchB** [comment]
Yes @kavita121 
You can also work on this.

**Comment by deepharshsri** [comment]
hey, can I know what is to be written on the logo?

**Comment by lelouchB** [comment]
Hey 👋
It should read

Final Space API

Thanks

**Comment by deepharshsri** [comment]
Let me clear, the above logo you have mentioned is your current logo and you want a new logo having the "Final  Space written and mooncake logo design " in it???

**Comment by lelouchB** [comment]
Mooncake is not a design but a character. I want the logo either text based that reads "Final Space API" or image based made with Final Space characters.
Thanks 

Here is mooncake

![image](https://user-images.githubusercontent.com/45850882/95320029-7e3e1500-08b6-11eb-8091-0b6b7bce333f.png)

**Comment by deepharshsri** [comment]
Sir, I have created a logo, and  what I understand you want to update the logo in the image folder of frontend and make a favicon so that when we click on that logo it goes to  "/api" path.

**Comment by lelouchB** [comment]
Hey, @deepharshsri No Sir required, we are all learners here.

You can send that logo in a PR to `endpoint`  branch and we will proceed from there. No faviocn required just yet.
Thanks

**Comment by lelouchB** [comment]
@kavita121 and @chandresh1339 
Any update on this ?
