### ISSUE TITLE
Add GitHub Star button to the Landing Page

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#24]
Add a GitHub star button on the landing page.

![image](https://user-images.githubusercontent.com/45850882/95198811-74a2a780-07f9-11eb-8daf-8b6b5a3b95a9.png)

Here is how docusaurus do it. https://v2.docusaurus.io/

![image](https://user-images.githubusercontent.com/45850882/95200866-b2ed9600-07fc-11eb-8883-b8ce9127a3d0.png)

You can refer to their code here.  https://github.com/facebook/docusaurus/blob/2e9854964d3ba7b79634de37d6971532e457a9b3/website/src/pages/index.js#L92

Make sure to add the accompanying `css`.

**Comment by Joaolfelicio** [comment]
Hi @lelouchB can you assign this to me?
Thanks.

**Comment by lelouchB** [comment]
@Joaolfelicio Of course
Let me know if you have any questions.

**Comment by lelouchB** [comment]
Hey @Joaolfelicio 
Is there any update on this?

Just checking in

Thanks

**Comment by Joaolfelicio** [comment]
Hi @lelouchB!
Still haven't had the time to, will implement this after I get off work today.
Thanks

**Comment by lelouchB** [comment]
Of course @Joaolfelicio 
No rush
 
Thanks

**Comment by Joaolfelicio** [comment]
Interesting project, let me know if you need help with something more elaborated in the FE.

**Comment by lelouchB** [comment]
@Joaolfelicio 
Ofcourse 

Thanks for your contributions.

**Comment by DarkDevCY** [comment]
Hello, is this still available?

**Comment by lelouchB** [comment]
> 
> 
> Hello, is this still available?

No @DarkDevCY This is already completed and is in process to ship to production.

You can try #32 if that interests you?

Thanks

**Comment by lelouchB** [comment]
Hey @Joaolfelicio 
I have shipped this to production 
Here is the blog for the same
https://finalspaceapi.com
