### ISSUE TITLE
Add 300x300px jpeg Images for new Characters 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#26]
#18  and #25

@stevenjburrows added 15 new characters to the database.

Before adding them to the API response, good 300x300px images are required.

Create images for thses new characters.

Refer #3 and #15 

Resources - https://final-space.fandom.com/wiki/Category:Characters

**Comment by mowens86** [comment]
Hi,

Did you need 300x300 images for these characters? https://github.com/lelouchB/final-space-api/pull/25/files

If no one has claimed this or is working on it, I'd be up to the task.

**Comment by lelouchB** [comment]
Yes @mowens86 
Thats correct we need images for these new characters 
#25 
I will assign this to you

**Comment by lelouchB** [comment]
@mowens86 
Amazing work
Really appreciate it.

Let me know if you are interested in other issues as well
I will ping you once these images are live and reflected in API response.
Thanks
