### ISSUE TITLE
Add 404 Page

### ISSUE THREAD

**Issue by mahendrarathore1742** [lelouchB/final-space-api#27]
After random url its not showing 404 not found page,

**Comment by lelouchB** [comment]
Hey @mahendrarathore1742 Can you share a screenshot for this and a random URL.

Thanks

**Comment by mahendrarathore1742** [comment]
it's showing Cannot GET /shdfdushfusdhfuashjkDJSDFHJSDBFHJSBDHJASB

**Comment by lelouchB** [comment]
Great 👍 
Amazing work
I will create an issue for this and assign it you 

Thanks

**Comment by lelouchB** [comment]
Please comment on #29 so I ca assign it to you.
Thanks
