### ISSUE TITLE
 Add 404 Page

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#29]
There is no 404 page, so add one. #27 

Head to https://finalspaceapi.com/404
Thanks @mahendrarathore1742 for this issue.

Error expected : 
![image](https://user-images.githubusercontent.com/45850882/95207303-5a6ec680-0805-11eb-916e-bfab6a816995.png)

**Comment by lelouchB** [comment]
hey @mahendrarathore1742
Comment on this issuse so I can assign it you.
Thanks

**Comment by mahendrarathore1742** [comment]
keep it up sir , you can do it,

**Comment by lelouchB** [comment]
Hey @mahendrarathore1742 
I don't quite follow.

Looking forward to your contributions

**Comment by ayush-git228** [comment]
Can I contribute to this.

**Comment by Skr-suyash** [comment]
I would like to contribute on this. It is nearly completed so please assign this to me

**Comment by lelouchB** [comment]
Hey @ayush-git228 
@mahendrarathore1742 is working on this issue.

I just created a new issue #31 let me know if you are interested in that issue.

**Comment by lelouchB** [comment]
@Skr-suyash 
Like I said @mahendrarathore1742 is working on this 
If you are done with your commit, feel free to send a PR.

I will take a look at your PR and @mahendrarathore1742  PR, merge both of them and revert one 
This is only if you have completed this issue.

Thanks

**Comment by lelouchB** [comment]
@Skr-suyash and @ayush-git228 
#31 is no longer available 
But you can contribute to #32 
Since there can be many examples, you both can contribute to it.

Thanks

**Comment by lelouchB** [comment]
Hey @mahendrarathore1742 
What is the progress on this?

**Comment by mahendrarathore1742** [comment]
> Hey @mahendrarathore1742
> What is the progress on this?

almost done!

**Comment by lelouchB** [comment]
@mahendrarathore1742 
Any word on this?

**Comment by lelouchB** [comment]
@mahendrarathore1742 
Since there is no update, I am unassigning you.

**Comment by lelouchB** [comment]
@Skr-suyash 
Still interested in this?

**Comment by Skr-suyash** [comment]
Sure, I can do this but I am not able to understand how to add a 404 page to be displayed in Docasaurus

**Comment by lelouchB** [comment]
@Skr-suyash 
Here is a resource on this, take your time. Go through them and try to implement them and let me know
https://v2.docusaurus.io/docs/static-assets/#caveats

Alternatively you can try exploring dousaurus GitHub repo for a fix.

**Comment by Skr-suyash** [comment]
I would like to work on this, let us see if it works. 😅

**Comment by lelouchB** [comment]
> I would like to work on this, let us see if it works. 😅

Go for it 👍
