### ISSUE TITLE
Update character images to be consistent (300x300)

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#3]
### Generate new images 300x300px  jpg format.

- [x]   **Indicates that the 300x300px image exists for that character.**

Here is the complete list of characters we need images for 

- [ ] Gary Goodspeed
- [ ] Mooncake
- [ ] Quinn Ergon
- [ ] Little Cato
- [ ] Avocato
- [ ] KVN
- [ ] Ash Graven
- [ ] Fox
- [ ] H.U.E
- [ ] Clarence
- [ ] Lord Commander
- [ ] Nightfall
- [ ] A.V.A
- [ ] Tribore
- [ ] John Goodspeed
- [ ] Sheryl Goodspeed
- [ ] Gary Goodspeed (Nightfall's timeline)
- [ ] Bolo
- [ ] Invictus
- [ ] Melanie Dewinter
- [ ] Harp Graven
- [ ] Shannon Thunder
- [ ] Chuck
- [ ] Septim
- [ ] Fraskenhaur

**Comment by SeguinLoic** [comment]
Hello ! 
Can i take this issue ? :)

**Comment by lelouchB** [comment]
Yes @SeguinLoic 

I will assign this issue to you.

Let me know if you have any questions. 

Which image are you planning of generating?

Thanks

**Comment by SeguinLoic** [comment]
Thank you ! 
I think i'll generate all of them ;)

**Comment by lelouchB** [comment]
@SeguinLoic 
Thank you
That will be really helpful. 

Just a suggestion,  make sure the images you generate either by editing images on the web or taking screenshots during the episode, are close up of face and upper body.


Thanks 🙂

**Comment by lelouchB** [comment]
@SeguinLoic 
I have shipped this to production
Check it out here 
https://finalspaceapi.com/api/v0/character
