### ISSUE TITLE
Add Headers to docs

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#31]
Currently  all of the docs under `frontend/docs` are missing headers.

Add the required headers for better SEO.

Refer here https://v2.docusaurus.io/docs/markdown-features#markdown-headers

P.S. you can leave the image part.

**Comment by dmb1107** [comment]
Can I be assigned to work on this?

**Comment by lelouchB** [comment]
Yeah Sure 
@dmb1107 
Thanks 
Looking forward to your contributions.
