### ISSUE TITLE
Add Examples to the Documentation 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#32]
There is only one example present right now in the documentation i.e. Live React Example which can be found here 
https://finalspaceapi.com/docs/react/

Docusarus uses React Live for the interactive coder so it will only support React.

Add more example with the language and frameworks of your choice.

Resource: 
https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

https://v2.docusaurus.io/docs/markdown-features/#interactive-code-editor

P.S. it doesn't necessarily have to be  a live example. You can add simple code snippets with their output too.

Here are a few  ideas for this 

**Completed**
- [x] Vue @bobluppes
- [x] Angular @guzbarraf
- [x]  Vanilla JS @PSmigielski
- [x] Vue+Axios @Devdre1909
- [x] React + Axios @fernandoamz
- [x] Svelte+ Axios @fullstackmafia

Rest is up to your imagination.

**Comment by fernandoamz** [comment]
@lelouchB, May I add an example with react + axios ?

**Comment by fernandoamz** [comment]
@lelouchB, May I add an example with Vainilla too? and with Ajax ?

**Comment by lelouchB** [comment]
Hey @fernandoamz 
Lets do one at a time, I am assigning you for React + Axios

After you are done with, if other are available
I will assign it you 
Thanks 

Looking forward to your contributions.

**Comment by fernandoamz** [comment]
HI @lelouchB, Could you share with me an example as to how to install Axios into docosaurus?

**Comment by fernandoamz** [comment]
HI @lelouchB, Could you share with me an example as to how to install Axios into docosaurus?

**Comment by fernandoamz** [comment]
👋 Hey @lelouchB, I am new on docusaurus, May you share me an example as to how to add an import into the `theme-live-codeblock`? I searched information but I couldn't resolve it. Thanks.

**Comment by lelouchB** [comment]
Hey , @fernandoamz 
Sorry for the late response 
I see that you have figured this issue out. Great 👍

**Comment by bobluppes** [comment]
Hey @lelouchB, could I make an example in Vue.js? Would very much like to try out your API at the same time ;)

**Comment by lelouchB** [comment]
@bobluppes 
Ofcourse
I will assign this issue to you as well.

**Comment by lelouchB** [comment]
@bobluppes 
If you could use the `episode` endpoint in the example.

https://finalspaceapi.com/docs/episode

**Comment by bobluppes** [comment]
Oh cool, is the endpoint finished now. Will definitely use it then. Expect a PR this evening or tomorrow morning

**Comment by PSmigielski** [comment]
Could i make vanilla JS and axios examples ?

**Comment by lelouchB** [comment]
> Could i make vanilla JS and axios examples ?

Sure @PSmigielski

**Comment by Devdre1909** [comment]
Hi @lelouchB, can I make Vue and Axios Examples?

**Comment by lelouchB** [comment]
@Devdre1909 
yeah Sure,
As you already know this will be static example.
Be as creative as you can.

Use `location` endpoint and add screenshot of the Output too.

**Comment by guzbarraf** [comment]
Hi @lelouchB, give me the example in angular

**Comment by lelouchB** [comment]
Awesome
Thanks @guzbarraf

**Comment by fullstackmafia** [comment]
Hi @lelouchB  - I took a look at this and I think it's awesome. Could I make an example with SvelteJS and Axios?

**Comment by lelouchB** [comment]
> 
> 
> Hi @lelouchB - I took a look at this and I think it's awesome. Could I make an example with SvelteJS and Axios?

@fullstackmafia  Sure, Go for It!
Let me know if you have any questions.
