### ISSUE TITLE
Add Docusarus PWA plugin

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#34]
Add this plugin and configure it with proper images and theme colors.

https://v2.docusaurus.io/docs/using-plugins#docusaurusplugin-pwa

Let me know if you have any questions.

**Comment by jadonwolffs** [comment]
Can I give this a go?

**Comment by lelouchB** [comment]
@jadonwolffs ofcourse.

Looking forward to your contributions.

**Comment by jadonwolffs** [comment]
I've configured it like their docs instruct and it seems to spawn a serviceworker and pre-cache assets but it doesn't seem to show the option to install from the browser as it's supposed to, any idea why?

**Comment by lelouchB** [comment]
Hey @jadonwolffs 
Can you send a PR with the changes.

I am sure it will be a small issue and we will tackle it. 👍
