### ISSUE TITLE
Add Docusaurus Google Analytics plugin

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#35]
Add this plugin

https://v2.docusaurus.io/docs/using-plugins#docusaurusplugin-google-analytics

P.S. you can leave the `trackingId` blank, I will fill it myself.

**Comment by PSmigielski** [comment]
i would love to tackle this task

**Comment by lelouchB** [comment]
@lelouchB awesome 👌 
Looking forward to your contributions. 
Thanks

**Comment by PSmigielski** [comment]
Should IP be anonymized?
