### ISSUE TITLE
Add Introduction to the Docs

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#36]
Currently the introduction to the API is  very small.

https://finalspaceapi.com/docs/

This is a documentation issue,  write a good introduction ot the API.

Word Limit - 250 to 300 words. This is just a suggestion, even if you end up writing 500 words, just send the PR  we will work something out.

**Comment by bobluppes** [comment]
Hi @lelouchB, I have going through te documentation a bit today and I would like to work on this. Could you assign this to me?

**Comment by lelouchB** [comment]
Hey @bobluppes 
I will assign this to you.

Looking forward to your contributions.
