### ISSUE TITLE
Contribute data to Episode endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#4]
# Reopened to include Season 3 Episodes

The `/episode` endpoint is currently in progress. 
Contribute data for individual episodes of Final Space in the given schema. 

Resource: https://final-space.fandom.com/wiki/Final_Space_Wiki

P.S. You can leave the field for `img_url`. 

You can send a PR with the data in JSON format to the `endpoint` branch under `episode` folder.

Here is the schema for `/episode` endpoint:

|Key|Type|Description|
|---|---|---|
|id|int|The id of the episode.
|name|string|The name of the episode.
|air_date|array|The air dates of the episode.
|director|string|Director of the episode.
|writer|string|Writer of the episode.
|characters|array|List of characters who have been seen in the episode.
|img_url|string (url)|Image from the episode.

- [x]   **Indicates that the data exists for that episode.**

Here is the complete list of episodes we need data for 

- [x] Chaper 1
- [x] Chaper 2
- [x] Chaper 3
- [x] Chaper 4
- [x] Chaper 5
- [x] Chaper 6
- [x] Chaper 7
- [x] Chaper 8
- [x] Chaper 9
- [x] Chaper 10

- [x] The Toro Regatta
- [x] The Happy Place
 - [x] The Grand Surrender
 - [x] The Other Side
 - [x] The Notorious Mrs. Goodspeed 
 - [x] The Arachnitects
 - [x] The First Times They Met
-  [x] The Remembered
-  [x] The Closer You Get
 - [x] The Lost Spy
 - [x] The Set Up
 - [x] The Descent Into Darkness
 - [x] The Sixth Key

**Comment by GerryLarios** [comment]
I would like to help, can you assign me this issue?

**Comment by lelouchB** [comment]
Ofcourse @GerryLarios 
 
You can find the data here 

https://final-space.fandom.com/wiki/Final_Space_Wiki

Let me know if have any questions. 

Thanks 😊

**Comment by GerryLarios** [comment]
Hello @lelouchB, where can I put the JSON with the episode's data?

**Comment by lelouchB** [comment]
Hey @GerryLarios 
I am creating a new branch `endpoint `
You can send the PR to that branch. 
You will find a folder named  `episode ` there. You can create the JSON file under it.

Thanks 😊

**Comment by GerryLarios** [comment]
@lelouchB Thanks! Working on it

**Comment by lelouchB** [comment]
@GerryLarios  Amazing work 👍 
Really appreciate it,

I will ping you once the endpoint is live. 
Thanks

**Comment by lelouchB** [comment]
Hey @GerryLarios 
I have shipped this to production 
Here is the blog for the same
https://finalspaceapi.com/blog/episode/

**Comment by lelouchB** [comment]
Hey @GerryLarios 
If interested, please let me know. Else I will re assign this issue to someone else.

Thanks
