### ISSUE TITLE
Add LIMIT param to Character endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#43]
Add the LIMIT parameter to the character endpoint.
Users can limit the number of responses from the API

Something like this 
https://finalspaceapi.com/api/v0/character?limit=4

This will result in first 4 characters in the Database

Resources 
https://stackabuse.com/get-query-strings-and-parameters-in-express-js/
https://expressjs.com/en/resources/middleware.html
 https://masteringjs.io/tutorials/express/req

**Comment by PSmigielski** [comment]
Can you assign me to this task?

**Comment by lelouchB** [comment]
@PSmigielski 
Sure
Let me know if you need any help.
Thanks

**Comment by PSmigielski** [comment]
i can't connect to remote mongodb database

**Comment by lelouchB** [comment]
Hey 
You can use a local database with test or dummy data.

**Comment by lelouchB** [comment]
Hey @PSmigielski 
 #49 and #51 #50  are somewhat related to this

See this comment:

https://github.com/lelouchB/final-space-api/pull/51#pullrequestreview-503771740

Both these code blocks will go in `helpers/options.js`  file.

Let me know if you have any questions

**Comment by lelouchB** [comment]
Hey @PSmigielski 
 #51 is finished, you can follow it and add a `limit` field to `helpers/options.js`.

Should be pretty straightforward.

**Comment by PSmigielski** [comment]
Ok

**Comment by Pervolarakis** [comment]
would you like me to do this one?
