### ISSUE TITLE
Add Documentation for Episode endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#45]
The `episode` endpoint will be live soon..

Refer to  #4 and #28 and #42 

Follow this:
https://finalspaceapi.com/docs/character

**Comment by MrDoomy** [comment]
Hi! 👋
I'd like to help, can you assign to me this issue?

**Comment by lelouchB** [comment]
Sure @MrDoomy 
Let me know if you have any questions.

**Comment by MrDoomy** [comment]
Chookity Pah! 😉

I make a draft locally, can I push my code on a new branch (and which one)?

I'd like to update this documentation with the real data structure. In fact, I'd to know what kind of array are `air_date` and `characters`: `string`s only? Or specific date formats? In the same way, what kind of data structure for `characters`: `string`s (again)? `id`s only? Or objects (like `/character` endpoint)? 🤔

**Comment by lelouchB** [comment]
Hey @MrDoomy  
you can send your PR to `episode` branch to the `frontend/docs/episode.md`

For the schema: refer to #28 and #42

Here is the data for first episode

```json
{
        "id": 1,
        "name": "Chapter 1",
        "air_date": "02/15/2018",
        "director": "Mike Roberts",
        "writer": "Olan Rogers",
        "characters": [
            "https://finalspaceapi.com/api/v0/character/1",
            "https://finalspaceapi.com/api/v0/character/2",
            "https://finalspaceapi.com/api/v0/character/3",
            "https://finalspaceapi.com/api/v0/character/5",
            "https://finalspaceapi.com/api/v0/character/6",
            "https://finalspaceapi.com/api/v0/character/9",
            "https://finalspaceapi.com/api/v0/character/11"
        ],
        "img_url": "https://static.wikia.nocookie.net/final-space/images/9/9a/Episode_1b.jpg/revision/latest/scale-to-width-down/1000?cb=20180323215650"
    }
```

**Comment by MrDoomy** [comment]
@lelouchB Thank you! 🙏 I'll do that.

**Comment by lelouchB** [comment]
Hey @MrDoomy 
I have shipped this to production 
Here is the blog for the same
https://finalspaceapi.com/docs/episode

**Comment by MrDoomy** [comment]
Very nice! 👌
I ❤️ **Final Space**, so keep doing a good job! 😎

**Comment by lelouchB** [comment]
@MrDoomy 
This is the blog
https://finalspaceapi.com/blog/episode

**Comment by MrDoomy** [comment]
@lelouchB
Thanks for the mention on the blog 🙏, but my hyperlink is broken:
~https://github.com/MrDommy~ => https://github.com/MrDoomy 😅

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB
> Thanks for the mention on the blog 🙏, but my hyperlink is broken:
> ~https://github.com/MrDommy~ => https://github.com/MrDoomy 😅
Oh
I am so sorry
I will update it just now.
Thanks for letting m know.

**Comment by lelouchB** [comment]
@MrDoomy 
Updated
