### ISSUE TITLE
Add SORT param to Character endpoint

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#49]
Add a sort parameter which lets the user sort the response based on `id`.

https://finalspaceapi.com/api/v0/character/?sort=desc
Return the response starting from 40

https://finalspaceapi.com/api/v0/character/?sort=asc
This response will be same as https://finalspaceapi.com/api/v0/character/  i.e. from 1 to 40.

So, https://finalspaceapi.com/api/v0/character/ is the same as https://finalspaceapi.com/api/v0/character/?sort=asc and they both return same response.

Resource: http://expressjs.com/en/api.html#req.query

**Comment by daretobedifferent18** [comment]
I want to work on this issue, pls assign this to me.

**Comment by lelouchB** [comment]
Sure @daretobedifferent18 

Looking forward to your contributions.

Let me know if you have any questions.

**Comment by daretobedifferent18** [comment]
https://finalspaceapi.com/api/v0/character/?sort=desc is returning in ascending order of id only, so I have to fix this?

**Comment by lelouchB** [comment]
Currently there is no SORT parameter, so every query will result in the same respone.
The issue is for creating one.

**Comment by Thanarathanam** [comment]
Sorry, @lelouchB @daretobedifferent18  When I saw this issue It was unassigned. So I started working. Now only I came back and see the comments

**Comment by lelouchB** [comment]
@Thanarathanam 
You should have commented to be assigned.
I guess I will merge both your and @daretobedifferent18 PR and revert one of them.

Thanks for your contribution

**Comment by daretobedifferent18** [comment]
> @Thanarathanam
> You should have commented to be assigned.
> I guess I will merge both your and @daretobedifferent18 PR and revert one of them.
> 
> Thanks for your contribution

Please review PR #51
