### ISSUE TITLE
Convert background of PWA images to transparent.

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#58]
following #48

Mooncake image  was used as PWA logo  but that image has grayish background which doesn't look good.

Your mission should you choose to accept it
Take this Mooncake image or another similar from web

![unnamed](https://user-images.githubusercontent.com/45850882/95356301-261e0780-08e4-11eb-9bed-c5b6d34062e3.png)

Generate icons  here https://www.pwabuilder.com/imageGenerator

And update the existing logo under `static/img/pwa`
Make sure rhe background is transparent.

Pretty straightforward  :)

**Comment by mayank** [comment]
@lelouchB All images need to be replaced? Including Splash screen?

**Comment by lelouchB** [comment]
> @lelouchB All images need to be replaced? Including Splash screen?

When you Generate logo from the website,  just replace everything in `pwa` folder. 

Remember to rename the image before generating images.

After updating test the build on your local machine.

Are you interested in this issue?

**Comment by jackie-kinsler** [comment]
I'm interested in this issue. Want me to work on it? Or @mayank, are you on it?

**Comment by lelouchB** [comment]
> I'm interested in this issue. Want me to work on it? Or @mayank, are you on it? 

Hey  @jackie-kinsler 
 
I am assigning this issue to you.

Let me know if you have any questions. 

Like I said it should be pretty straightforward.
