### ISSUE TITLE
Make the main README more informative and nice-looking

### ISSUE THREAD

**Issue by Skr-suyash** [lelouchB/final-space-api#60]
**Is your feature request related to a problem? Please describe.**
The README lacks some important features related to contribution for beginners and some other features need to be added.

**Describe the solution you'd like**
Adding badges and writing a clear and concise guideline for contribution

**Additional context**
I would be adding some badges to give it a modern look and some other edits

**Comment by Skr-suyash** [comment]
Please assign this issue to me

**Comment by lelouchB** [comment]
@Skr-suyash 
I am assigning this to you.

Just make sure the changes are significant and valuable. 

Thanks
