### ISSUE TITLE
Add data seeder to backend 

### ISSUE THREAD

**Issue by mhalsubhi** [lelouchB/final-space-api#64]
When cloning a project locally, there is no data to start with for testing or experiment with, so it will be nice if there's a seeder to seed data to the local database.

I'm thinking of adding an npm script called `seed` so we will have command `npm run seed` to seed local database with current actual data fetched from [api](https://finalspaceapi.com/api/v0/character)

so basically the `npm run seed` will:-

1. connect to local database
2. fetch data from api.
3. seed local database.

I think the file will be named `seeder.js` and it will be in the root of [backend](https://github.com/lelouchB/final-space-api/tree/main/backend) folder and use [Axios](https://github.com/axios/axios) as dev dependency

If you like the idea assign it to me so I'll give it a shot

**Comment by kunaljain0212** [comment]
@mhalsubhi  Can I work on this issue, please?

**Comment by guzbarraf** [comment]
Hello, I would like to collaborate with this

**Comment by lelouchB** [comment]
@mhalsubhi  
This is awesome, this was on my ToDo.

Thanks for making an issue for this.

@guzbarraf  sure, you both can collaborate on this.

I will assign this to both of you. 💯

**Comment by mhalsubhi** [comment]
@lelouchB sure, I would like to collaborate with @guzbarraf, so we will divide it into two tasks

1. fetch data from API using [Axios ](https://github.com/axios/axios)as dev dependency. 
2. seed database with fetched data with `npm run seed`.

@guzbarraf choose what task you would like to work on and I'll pick the other one 👍🏼

**Comment by guzbarraf** [comment]
I am happy to collaborate with you @mhalsubhi and I take the first task

**Comment by mhalsubhi** [comment]
@guzbarraf  so I'm I 👍🏼 , we will create `seeder.js` in the `backend` folder, in the file data will be fetched using Axios, after you complete it, please mention me so I can use your fetched data to seed database.

**Comment by lelouchB** [comment]
Hey @guzbarraf and @mhalsubhi 
See #85 
You can use this in the issue.

**Comment by mhalsubhi** [comment]
@lelouchB ok 👍🏼, If you want this to be done quickly, I will work on it and send PR shortly

**Comment by lelouchB** [comment]
@mhalsubhi 
I will appreciate if it can be done quickly  but I am in no rush. 
Take your time. 
Thanks 😊

**Comment by mhalsubhi** [comment]
@lelouchB @guzbarraf  I'm excited to apply this feature, so I send PR #91 👍🏼

**Comment by guzbarraf** [comment]
@lelouchB i have the code for the task 1

**Comment by lelouchB** [comment]
> @lelouchB i have the code for the task 1

@guzbarraf 
I guess this issue is almost complete
But you can go ahead and send the PR, I will approve it so that it can be counted as a valid Hacktoberfest contribution. 

Can you let me know what king of issues you are interested on frontend, backend, test, bugs, etc.
And I will try to come up with an issue for you and assign it you .

Thanks

**Comment by guzbarraf** [comment]
@lelouchB 
that sounds great i will submit the PR and be interested in some frontend.

Thanks

**Comment by lelouchB** [comment]
> @lelouchB
> that sounds great i will submit the PR and be interested in some frontend.
> 
> Thanks

Great 👍 
I will create some frontend issues and mention you.
How about #32 ?
You have to create examples in language and frameworks of your choice.
