### ISSUE TITLE
Bug in readme npm command

### ISSUE THREAD

**Issue by bobluppes** [lelouchB/final-space-api#67]
**Describe the bug**
The frontend contributing section of the readme states to run `npm run server`. However, `server` is not recognized an an npm script.

**To Reproduce**
1. Navigate to '/frontend`
2. Run `npm run build`
3. Run `npm run server`

**Expected behavior**
The development server is expected to spawn on `localhost:3000`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N.A.

**Additional context**
Encountered on the CLI

**Comment by lelouchB** [comment]
#66 solved this.
Thanks @bobluppes
