### ISSUE TITLE
Add LIMIT param Documentation

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#75]
Following #43 and #74  
Limit param will soon be shipped to production, add proper documentaion to both `character`  and `endpoint` .

Follow this as inspiration 
https://finalspaceapi.com/docs/character#sort-the-response

**Comment by lelouchB** [comment]
@Pervolarakis
Interested in this one ?

**Comment by mhalsubhi** [comment]
Hello @lelouchB may I take this one?

**Comment by lelouchB** [comment]
Yes, @mhalsubhi 
If you can do this quickly.

Thanks

**Comment by mhalsubhi** [comment]
@lelouchB ok 👍🏼  I'm on it

**Comment by lelouchB** [comment]
> 
> 
> @lelouchB ok 👍🏼 I'm on it

Thanks 👍 
The thing is I am about to ship LIMIT into production and wanted the documentation to be completed as soon as possible.
Thanks for your understanding.

**Comment by lelouchB** [comment]
Hey @mhalsubhi 
Also include something like this 
```
https://finalspaceapi.com/api/v0/character/?limit=4&sort=desc
```
