### ISSUE TITLE
Add limit query to React example

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#80]
Live Example on https://finalspaceapi.com/docs/react
is currently using `data.slice(0,5)` to limit the character cards..

Now that `limit` query is finished, update this example with the `limit` query.

Resource 
https://finalspaceapi.com/docs/character#limit-the-response

**Comment by PSmigielski** [comment]
can you assign me to this task?

**Comment by lelouchB** [comment]
@PSmigielski 
Ofcourse
