### ISSUE TITLE
All Endpoints Except `/` are Broken on Development

### ISSUE THREAD

**Issue by CodingCarter** [lelouchB/final-space-api#81]
**Describe the bug**
I just followed all steps mentioned in the README for running the backend in development.  After running `npm run serve` in the `backend` directory, though, `localhost:8000` is not returning any data when sending a request to `http://localhost:8000/api/v0/character` or any of the other endpoints besides `http://localhost:8000/api/v0/`.

**To Reproduce**
1. `gh repo clone lelouchB/final-space-api`
3. `cd final-space-api`
2. `cd backend`
3. `npm install`
4. `npm run dev`
5. go to [http://localhost:8000/api/v0/character](http://localhost:8000/api/v0/character)

**Expected behavior**
The server should be returning the actual data

**Screenshots**
![image](https://user-images.githubusercontent.com/43641633/95467055-a1aea180-0942-11eb-8262-420d70592cb5.png)
![image](https://user-images.githubusercontent.com/43641633/95467111-b2f7ae00-0942-11eb-98ac-0ed7eae1f085.png)
![image](https://user-images.githubusercontent.com/43641633/95467160-c145ca00-0942-11eb-860c-beb50b2285b5.png)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version 85

**Comment by lelouchB** [comment]
@CodingCarter 
I know about this 
This is already in progress in #64 to add test data for local dev environment
So, I am going to close this issue.
Thanks

**Comment by JuanVqz** [comment]
It is because as you can see in your image above you haven connection with the database

**Comment by lelouchB** [comment]
@JuanVqz and @CodingCarter 
Only the droplet have connection to database.

@CodingCarter 
You can use dummy data for now.
