### ISSUE TITLE
Add Announcement Bar to Frontend

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#83]
Docusaurus has a very cool announcement bar:

![image](https://user-images.githubusercontent.com/45850882/95468997-b6b81e80-099c-11eb-8cd3-8a79155737da.png)

Add something similiar to this to `frontend`. 
**Please don't copy it as it is, add some original text to engage the visitors like a small fun or comic quote.**

Resource
https://v2.docusaurus.io/docs/theme-classic/#announcement-bar

**Comment by MrDoomy** [comment]
Hi @lelouchB 👋
I'd like to work on it tonight, can you assign this to me? 🙂

**Comment by lelouchB** [comment]
Of course @MrDoomy  👍 
I will assign this to you.

Thanks

**Comment by MrDoomy** [comment]
Hello again @lelouchB
I just create a PR right here 👉 https://github.com/lelouchB/final-space-api/pull/88
Let me know if it doesn't fit, I'll change that quickly 😉

**Comment by lelouchB** [comment]
@MrDoomy 
It is perfect 
I will ship it to production sometime tommorow. 

Thanks 😊
