### ISSUE TITLE
Update output of base endpoint in docs/intro

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#89]
Following  #78 
The response from `https://finalspaceapi.com/api/v0` has changed but the same has not been updated here 
https://finalspaceapi.com/docs/

Update the output of the base endpoint. 
https://github.com/lelouchB/final-space-api/blob/main/frontend/docs/intro.md

**Comment by PPInfy** [comment]
Can I take it?

**Comment by lelouchB** [comment]
Hey @PPInfy 
Yeah sure
I will assign it you 

Let me know if you have any questions.

**Comment by PPInfy** [comment]
Done in PR #96 . Please check.

**Comment by lelouchB** [comment]
@PPInfy 
Nice Work 👍
