### ISSUE TITLE
Generate 300x300 images for location endpoint 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#97]
Following  #95 location endpoint will be live soon.

Create images for all the different locations present in #95

Images should be 300x300 jpeg

**Comment by ErickLemos** [comment]
I would like to contribute on this

**Comment by fgxhammer** [comment]
Hey i would take a look at this! Please assign.

**Comment by MrDoomy** [comment]
Hey @lelouchB 👋
I started to work on this part. I already have a set of thumbnails for the 400x300 resolution (the 300px width being too small)... Could this match? 🤔

**Comment by lelouchB** [comment]
> 
> 
> Hey @lelouchB 👋
> I started to work on this part. I already have a set of thumbnails for the 400x300 resolution (the 300px width being too small)... Could this match? 🤔

Awesome 👍 
400x300 is great too.
I will assign this to you.
Thanks

**Comment by lelouchB** [comment]
Hey @MrDoomy 
https://finalspaceapi.com/blog/location
Its live
