### ISSUE TITLE
Add documentation for Location endpoint 

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#98]
Following #95 and #97
Add documentation for location endpoint 

You can take reference from episode and character endpoint documentation.

**Comment by tim-richter** [comment]
Hey @lelouchB , I could give this a shot!

**Comment by lelouchB** [comment]
Sure @tim-richter 
I will assign this to you.

**Comment by lelouchB** [comment]
Hey @tim-richter 
https://finalspaceapi.com/blog/location
Its live
